### ISSUE TITLE
Client - world disappears when looking exactly vertically up or down.

### ISSUE THREAD

**Issue by UnknownShadow200** [SirCmpwn/TrueCraft#101]
The look at matrix does not work when the target position is exactly parallel to the up vector. (You end up with NaN in some of the elements)

It's an easy fix though, just change 
```csharp
 Client.Pitch = MathHelper.Clamp(Client.Pitch, -90, 90);
```
in TruecraftGame.UpdateKeyboard to
```csharp
 Client.Pitch = MathHelper.Clamp(Client.Pitch, -89.9f, 89.9f);
```

**Comment by SirCmpwn** [comment]
Sounds like a great chance for a pull request?
