### ISSUE TITLE
Adding documentation

### ISSUE THREAD

**Issue by mrpimpunicorn** [SirCmpwn/TrueCraft#117]
Most (if not all) of the codebase is undocumented or lacking comments. I would be willing to go through and add Intellisense-style commenting to any methods and classes I can think of appropriate comments for, if warranted.

**Comment by SirCmpwn** [comment]
XML comments are fine, but I'm of the opinion that the codebase is well organized and easy to read without comments.

**Comment by mrpimpunicorn** [comment]
Yeah, the code is easy to understand by itself, just thinking about mods/plugins being quicker to develop without having to jump into the server/client code non-stop.

**Comment by SirCmpwn** [comment]
Yeah, XML comments are a good idea. Particularly in TrueCraft.API.

**Comment by mrpimpunicorn** [comment]
Okay, I'll start looking at it. Thanks for the confirmation.

**Comment by SirCmpwn** [comment]
I don't think this issue is necessary at this point. Feel free to send more documentation PRs.
