### ISSUE TITLE
Force exit

### ISSUE THREAD

**Issue by iBars** [SirCmpwn/TrueCraft#137]
Force exit on Windows while loading the world: http://i.imgur.com/TiRG3g1.jpg

**Comment by SirCmpwn** [comment]
Can someone on Windows take a look at this?

**Comment by mrpimpunicorn** [comment]
Testing now.

**Comment by SirCmpwn** [comment]
Hold on, it's (partially) my fault.

**Comment by SirCmpwn** [comment]
By partially I mean entierly

**Comment by SirCmpwn** [comment]
Okay, 9bd1db8317c825d217bfcd4b329c4bcba538e838 should fix this for the nightlies. Someone will have to come add Windows-specific versions of [these commands](https://github.com/SirCmpwn/TrueCraft/blob/master/TrueCraft.Launcher/TrueCraft.Launcher.csproj#L23-L28) (ditto on line 38) to get the *build* working on Windows again.

**Comment by SirCmpwn** [comment]
Fuck, it's still not working. xbuild is a real pain in the ass.

**Comment by mrpimpunicorn** [comment]
I've cleared out my build directory and pulled the latest commits, and I can still compile and run :100:?
Regardless, the Windows versions of those commands are ``` del ``` and ``` copy ```, respectively. Parameters don't need to be moved.

**Comment by SirCmpwn** [comment]
It's a little complicated. Wait until I push another change to see how it works (and try running `git clean -fdX` before testing).

**Comment by SirCmpwn** [comment]
Alright, 94fc3b08b84ea00dc89c07d515f0a40c98f432b6 should *actually* fix it and has a placeholder for someone to add Windows support. I'm not going to do it personally becasue I don't have any means of testing it.

**Comment by SirCmpwn** [comment]
@iBars can you [download](http://truecraft.io/download) the latest build and try it out?

**Comment by mrpimpunicorn** [comment]
Is building working on Linux? I've got a fix for Windows, just need to know if I should apply the fix to both.

**Comment by SirCmpwn** [comment]
It builds fine on Linux.

**Comment by mrpimpunicorn** [comment]
Okay, I'll just apply the fix to Windows then.

**Comment by iBars** [comment]
World loaded and I see lightblue screen, but I see 1/4 half of launcher window (bottom right) and then my computer going to glitches, so then I required to force power off computer, because even task scheduler (Ctrl+Alt+Delete) don't appear from lags...

**Comment by SirCmpwn** [comment]
Well, that's not good. I don't know what's up there. Are any other Windows users having issues?

**Comment by manio143** [comment]
Well, the window position is a bit of a problem, since mono captures the mouse completely and you can't move it. But the rest works fine for me. The lightblue screen is because it starts pointed at the sky.

**Comment by SirCmpwn** [comment]
FWIW you can press tab to release the mouse.

**Comment by UnknownShadow200** [comment]
Maybe the client should also check the 'IsActive' property in OnMouseComponentMove and only handle mouse move events (and resetting the mouse position) when the window has focus?

**Comment by SirCmpwn** [comment]
Sounds like a good idea, @UnknownShadow200.
