### ISSUE TITLE
Water is rendering... purple?

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/TrueCraft#138]
This might have something to do with precomputed textures. Making an issue for it because I have no clue what's wrong, maybe someone else can figure it out.

**Comment by mrpimpunicorn** [comment]
Screenshot?

**Comment by SirCmpwn** [comment]
![](https://sr.ht/cf26.png
)

**Comment by SirCmpwn** [comment]
Ice looks fine:

![](https://sr.ht/284d.png
)

**Comment by SirCmpwn** [comment]
Opened a thread on the MonoGame support website: http://community.monogame.net/t/semi-transparent-textures-rendering-as-purple/2636

**Comment by mrpimpunicorn** [comment]
We actually use AlphaTestEffect for transparent objects.

**Comment by SirCmpwn** [comment]
Ah, I didn't know that was changed. I'll edit my topic.

**Comment by SirCmpwn** [comment]
Can anyone reproduce this? Is it a Linux only bug?

**Comment by mrpimpunicorn** [comment]
I've changed how I disable color channel writing as well as went back to using BasicEffect, I still can't reproduce. You could change the texture to a lighter blue to dampen the effect for now.

**Comment by cra0zy** [comment]
https://github.com/mono/MonoGame/issues/2238

**Comment by SirCmpwn** [comment]
Thanks @cra0zy. I'll see what I can do about taht.
