### ISSUE TITLE
Minecraft query protocol support

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/TrueCraft#139]
We need to support the [query](http://wiki.vg/Query) protocol at some point.

**Comment by manio143** [comment]
I'd be happy to take a look at it.

**Comment by SirCmpwn** [comment]
Great :smile:

**Comment by manio143** [comment]
I stumbled upon a bit of a problem. I know that MOTD, port, etc. is in `ServerConfiguration`, but the server itself has no reference to it. How does it even send motd to newly logged on users?

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/TrueCraft/blob/master/TrueCraft/Handlers/LoginHandlers.cs#L61-L62

**Comment by manio143** [comment]
Ok, thanks, didn't notice it was static.

**Comment by SirCmpwn** [comment]
:smile:
