### ISSUE TITLE
Speeding up chunk rendering

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/TrueCraft#141]
ITT we discuss strategies for speeding up the [chunk renderer](https://github.com/SirCmpwn/TrueCraft/blob/master/TrueCraft.Client/Rendering/ChunkRenderer.cs).

**Comment by mrpimpunicorn** [comment]
As discussed earlier, rendering on a per-face basis will speed up rendering performance. Basically, if a block is 'simple' (just a cube, no transparency, no special shape, opaque only), then render it per-face by checking which of its neighboring blocks are 'simple' too and ignoring those faces, drawing the others. If a block isn't 'simple', these kinds of optimizations get out of hand pretty quickly, so we can just draw that kind of block whole for now.

**Comment by UnknownShadow200** [comment]
Solid and transparent blocks should be rendered in the same pass. (using alpha test)

Only translucent blocks such as water, nether portal and ice should be rendered with a depth pass then the actual pass.

**Comment by mrpimpunicorn** [comment]
@UnknownShadow200 I went to test out your first point and it works well, the only issue is that AlphaTestEffect doesn't have support for lighting, is there a way we can write a custom effect or use alpha test with BasicEffect?

**Comment by SirCmpwn** [comment]
This is she was about the actual process of converting chunks to the set of vertices and indices.

**Comment by SirCmpwn** [comment]
Issue* on mobile

**Comment by mrpimpunicorn** [comment]
I assumed so, when I talk about rendering blocks I really mean generating their mesh data.

**Comment by UnknownShadow200** [comment]
The SharpDevelop profiler suggested that retrieving 'DateTime.Now' in Chunk.GetBlockId was responsible for 70% of the time taken to build chunk meshes.

Changing to DateTime.UtcNow reduced average mesh building time from 140 to 50 ms. (Not sure if impact with Mono is quite so severe)

**Comment by SirCmpwn** [comment]
I have no idea why we need to keep track of the time chunks are being *accessed* anyway. It's only there because vanilla Minecraft has a property for it in chunk NBT data. I'm going to remove it entirely.

I'm not really convinced that working with faces instead of blocks will speed things up much in the chunk renderer, but I want to do it anyway for the sake of improving the framerate once the main thread gets it.

**Comment by mrpimpunicorn** [comment]
Yeah, I just went and commented out the date tracking to see the performance improvements; chunks rendered almost instantly.

**Comment by SirCmpwn** [comment]
Oh, I see why it's there. I'll fix that up in a minute.

**Comment by SirCmpwn** [comment]
Wow, way better without that.

**Comment by SirCmpwn** [comment]
So much so that I'm just going to close this.
