### ISSUE TITLE
TrueCraft players float a little ways over the ground

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/TrueCraft#146]
If you log into a server with a TrueCraft client and a Minecraft client, the TrueCraft player will appear to hover a little bit over the ground.

**Comment by manio143** [comment]
I also noticed that after I connected with TrueCraft to the server and exited, when I connected with Minecraft client the player from TrueCraft session is still there. (I logged in via TrueCraft twice)

![2015-06-24_20 39 53](https://cloud.githubusercontent.com/assets/10709060/8338414/42620c4c-1ab1-11e5-8279-a0c8dbfe62f4.png)

**Comment by SirCmpwn** [comment]
That's a separate bug, I'm aware of it.
