### ISSUE TITLE
Grass needs to be tinted to biome colors

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/TrueCraft#147]
Biomes are entirely out of scope until feature parity is reached, but we should color them some shade of green so that non-default texture packs don't look like shit.

![](https://sr.ht/951d.png)

I think this will require a custom shader (rather than BasicEffect), and we should probably consider it around the same time we work on lighting.

**Comment by NSDex** [comment]
I briefly touch on this subject in the Lighting wiki page.  The biome tinting color is part of the computation to produce the vertex color.

**Comment by mrpimpunicorn** [comment]
We can stick with ```BasicEffect``` if I'm not mistaken by writing a custom vertex structure that implements ```IVertexType``` and gives us; position, normal, color, and texture coords. Then just replace everywhere we used ```VertexPositionNormalTexture``` with this new struct.

**Comment by SirCmpwn** [comment]
But using the additional fields given by the new struct requires a custom shader, no?

**Comment by mrpimpunicorn** [comment]
No, XNA automagically glues our vertex fields to their implementation using a custom ```VertexDeclaration``` instance provided by us. See [this article](https://msdn.microsoft.com/en-us/library/bb976065.aspx) on MSDN. Color, texture and lighting support is already baked into ```BasicEffect```, XNA just doesn't expose a pre-made vertex class that holds all those fields.

**Comment by SirCmpwn** [comment]
Oh, that's super nifty. That makes things a lot easier. Will we be able to get away with implementing block light without a shader, then?

**Comment by mrpimpunicorn** [comment]
Yes we could, but I think it would be better to just eventually implement deferred rendering instead; A better use of per-vertex colors for lighting would be ambient occlusion.

**Comment by mrpimpunicorn** [comment]
See [this article](http://0fps.net/2013/07/03/ambient-occlusion-for-minecraft-like-worlds/); AO is dead simple in a voxel-based game.

**Comment by SirCmpwn** [comment]
I guess at some point we'll just have to bite the bullet and write a shader.

**Comment by NSDex** [comment]
I haven't investigated the smooth lighting stuff in my decompiled minecraft but I believe AO is also backed into the vertex color.
