### ISSUE TITLE
Custom chat colors

### ISSUE THREAD

**Issue by cubrr** [SirCmpwn/TrueCraft#16]
When starting to implement the custom client, I don't think it would be a bad idea to implement custom chat colors for modding support.

E.g. instead of using the predefined colors like `$9` for blue, a mod could use RGB values like `$(0,116,217)` for a slightly nicer blue.

Too rad?

**Comment by SirCmpwn** [comment]
Added a "future" label.

**Comment by cubrr** [comment]
Thanks!

**Comment by SirCmpwn** [comment]
Let's leave it open. I don't close issues until they're resolved.
