### ISSUE TITLE
Render target block with outline

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/TrueCraft#164]
We need to render an outline around the block the mouse is pointed at. We also need to draw crosshairs on the screen with additive alpha (watch the crosshairs closely in Minecraft to see why).

When this feature is implemented, it would also be a good time to keep track of the target block and the face the mouse is pointing at for the sake of placing blocks against it later.

**Comment by UnknownShadow200** [comment]
Some good basis code for voxel traversal:
https://web.archive.org/web/20120113051728/http://www.xnawiki.com/index.php?title=Voxel_traversal
* Make sure that after finding a voxel, test the ray-boundingbox intersection as not all blocks occupy a whole voxel. Some code for that: http://www.cs.utah.edu/~awilliam/box/box.pdf

The voxel traversal code appears to be public domain according to https://web.archive.org/web/20120112084122/http://www.xnawiki.com/index.php?title=XNAWiki:About. I couldn't find any explicit licensing for the ray-box intersection, but presumably credit should be given.

**Comment by SirCmpwn** [comment]
Done.
