### ISSUE TITLE
Inverted directions of head movement

### ISSUE THREAD

**Issue by manio143** [SirCmpwn/TrueCraft#167]
So I launched both Minecraft and TrueCraft clients and watched the Minecraft one while rotating camera on TrueCraft. The head of the TrueCraft player rotates in opposite directions than the camera. Both horizontally and vertically.

**Comment by Luigifan** [comment]
What operating system is this under?

**Comment by manio143** [comment]
Windows.

**Comment by SirCmpwn** [comment]
This has been fixed as of today.
