### ISSUE TITLE
Can't find fNbt.csproj

### ISSUE THREAD

**Issue by jchappelle** [SirCmpwn/TrueCraft#175]
I installed monodevelop successfully and mostly pulled in the project successfully except it can't find fNbt.csproj or the fNbt namespace.

Any help is appreciated.

**Comment by SirCmpwn** [comment]
Have you ever wondered about the origin of the term "readme"?

https://github.com/SirCmpwn/TrueCraft#compiling

**Comment by jchappelle** [comment]
Thanks smart ass.

I read this and it was a little misleading.

https://github.com/SirCmpwn/TrueCraft/wiki/compiling

On Sat, Jun 27, 2015 at 6:54 PM, Drew DeVault <notifications@github.com>
wrote:

> Have you ever wondered about the origin of the term "readme"?
>
> https://github.com/SirCmpwn/TrueCraft#compiling
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SirCmpwn/TrueCraft/issues/175#issuecomment-116166682>.
>

-- 



NOTICE: This electronic mail message and any files transmitted with it are 
intended exclusively for the individual or entity to which it is addressed. 
The message, together with any attachment, may contain confidential and/or 
privileged information. Any unauthorized review, use, printing, saving, 
copying, disclosure or distribution is strictly prohibited. If you have 
received this message in error, please immediately advise the sender by 
reply email and delete all copies.

**Comment by SirCmpwn** [comment]
I don't know why that page exists. I removed it.

**Comment by jchappelle** [comment]
Cool. Thank you. I'll give the readme a shot

On Sat, Jun 27, 2015 at 7:58 PM, Drew DeVault <notifications@github.com>
wrote:

> I don't know why that page exists. I removed it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SirCmpwn/TrueCraft/issues/175#issuecomment-116178250>.
>

-- 



NOTICE: This electronic mail message and any files transmitted with it are 
intended exclusively for the individual or entity to which it is addressed. 
The message, together with any attachment, may contain confidential and/or 
privileged information. Any unauthorized review, use, printing, saving, 
copying, disclosure or distribution is strictly prohibited. If you have 
received this message in error, please immediately advise the sender by 
reply email and delete all copies.

**Comment by jchappelle** [comment]
I'm a java developer and I'm not used to this environment.

I'm running the server no problem, simply by hitting f5 in monodevelop.

How do I run the client?

On Sat, Jun 27, 2015 at 7:59 PM, Josh Chappelle <jchappelle@4redi.com>
wrote:

> Cool. Thank you. I'll give the readme a shot
>
> On Sat, Jun 27, 2015 at 7:58 PM, Drew DeVault <notifications@github.com>
> wrote:
>
>> I don't know why that page exists. I removed it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/SirCmpwn/TrueCraft/issues/175#issuecomment-116178250>
>> .
>>
>
>

-- 



NOTICE: This electronic mail message and any files transmitted with it are 
intended exclusively for the individual or entity to which it is addressed. 
The message, together with any attachment, may contain confidential and/or 
privileged information. Any unauthorized review, use, printing, saving, 
copying, disclosure or distribution is strictly prohibited. If you have 
received this message in error, please immediately advise the sender by 
reply email and delete all copies.

**Comment by SirCmpwn** [comment]
Right click (in monodevelop) `TrueCraft.Launcher` and set it as the start-up project, then hit F5 again.

**Comment by jchappelle** [comment]
Awesome. Thanks for the quick response.

On Sat, Jun 27, 2015 at 8:56 PM, Drew DeVault <notifications@github.com>
wrote:

> Right click (in monodevelop) TrueCraft.Launcher and set it as the
> start-up project, then hit F5 again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SirCmpwn/TrueCraft/issues/175#issuecomment-116182526>.
>

-- 



NOTICE: This electronic mail message and any files transmitted with it are 
intended exclusively for the individual or entity to which it is addressed. 
The message, together with any attachment, may contain confidential and/or 
privileged information. Any unauthorized review, use, printing, saving, 
copying, disclosure or distribution is strictly prohibited. If you have 
received this message in error, please immediately advise the sender by 
reply email and delete all copies.

**Comment by lantianning** [comment]
I press your suggestion to do still error.
where is the fNbt.csproj?

**Comment by SirCmpwn** [comment]
RTFM, dude
