### ISSUE TITLE
Disconnecting a player with username already in use

### ISSUE THREAD

**Issue by manio143** [SirCmpwn/TrueCraft#176]
Since having two clients use the same username can result in loss in progress and other problems I decided to write a patch. But I wanted to make sure what would be the policy here:

a) Disconnect the second client during login
b) Kick the first one and let the second one login

**Comment by UnknownShadow200** [comment]
Standard minecraft server kicks the first client.

**Comment by SirCmpwn** [comment]
Kick the new client during login.
