### ISSUE TITLE
Usernames in logs are prefixed by the chat color identifier

### ISSUE THREAD

**Issue by cubrr** [SirCmpwn/TrueCraft#19]
![](http://i.imgur.com/tym5AyL.png)

The `SendMessage` method in the `MultiplayerServer` class should probably remove the chat color before writing the message to the log, otherwise we'll get messages like the one above.
~~I'd suggest a Regex fix which I have included in the commit (removed)~~

**Comment by SirCmpwn** [comment]
I would prefer not to use a regex-based solution, but I agree that removing them is productive.

**Comment by cubrr** [comment]
> I would prefer not to use a regex-based solution, but I agree that removing them is productive.

If you're worried about performance, we could replace
```c#
public static readonly Regex PrefixRegex = new Regex("^(?i)§[0-9a-f]");
```
with
```c#
public static readonly Regex PrefixRegex = new Regex("^(?i)§[0-9a-f]", RegexOptions.Compiled);
```

**Comment by SirCmpwn** [comment]
Don't use a screwdriver as a hammer. And compiling the regex is still far less performant than what would be a very simple purpose-built solution, especially on Mono.

**Comment by cubrr** [comment]
> Don't use a screwdriver as a hammer. And compiling the regex is still far less performant than what would be a very simple purpose-built solution, especially on Mono.

Okay, well...does this look like a viable solution?

```c#
public void SendMessage(string message, params object[] parameters)
{
    var compiled = string.Format(message, parameters);
    foreach (var client in Clients)
        client.SendMessage(compiled);
    Log(LogCategory.Notice, ChatColor.TrimColor(compiled));
}

// ...

private static readonly char[] Colors =
{
    '0', '1', '2', '3',
    '4', '5', '6', '7',
    '8', '9', 'a', 'b',
    'c', 'd', 'e', 'f'
};

public static bool IsStringColored(string text)
{
    if (text == null || text.Length < 2)
        return false;
    return text[0] == '§' && Colors.Contains(text[1]);
}

public static string TrimColor(string text)
{
    return IsStringColored(text) ? text.Substring(1) : text;
}
```

**Comment by SirCmpwn** [comment]
Nope. That would only work if the color is the first character.

**Comment by cubrr** [comment]
> Nope. That would only work if the color is the first character.

So colors can be anywhere in the message? Sorry, the code only uses the colors at the beginning so I didn't think it through I guess

**Comment by SirCmpwn** [comment]
Yep, colors can be anywhere in Minecraft chat messages.

**Comment by cubrr** [comment]
> Yep, colors can be anywhere in Minecraft chat messages.

Right. Will there be a need to check if the character after the `§` symbol is actually a color or...?

**Comment by SirCmpwn** [comment]
They should just be removed. The Minecraft client will crash if you send it invalid colors, for example, so we can probably safely assume that they can be removed completely.

**Comment by cubrr** [comment]
> They should just be removed. The Minecraft client will crash if you send it invalid colors, for example, so we can probably safely assume that they can be removed completely.

Okay, gotcha. I'll come up with something.
