### ISSUE TITLE
Snow blocks can be overwritten as if they were air on vanilla

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/TrueCraft#194]
but not on TrueCraft.

**Comment by StianTheDark** [comment]
How about adding a couple of "overridable" blocks. When placing blocks, if there - at the target location - is an overiddable block then delete that block and replace it with the one you're placing. Grass is also overriden I believe.

**Comment by SirCmpwn** [comment]
Actually, grass doesn't work that way. I thought it did, but my testing in b1.7.3 proved that wrong.

**Comment by StianTheDark** [comment]
Huh. Well, for mods it might be a good idea anyway. Maybe some better wording though, I mean, "overiddable" is kind of confusing.

**Comment by SirCmpwn** [comment]
Perhaps. Currently done [like this](https://github.com/SirCmpwn/TrueCraft/blob/master/TrueCraft.Core/Logic/BlockProvider.cs#L120-L127). Could be better for sure.
