### ISSUE TITLE
Current logo is not support with WPF 

### ISSUE THREAD

**Issue by snys98** [SirCmpwn/TrueCraft#197]
As I tested, the current logo is in format of .svg which is not supported in WPF. Thus Xwt.WPF won't load the logo. Hope fixed.

**Comment by SirCmpwn** [comment]
Seems like an easy target for a pull request if anyone wanted to send one along.

**Comment by mrpimpunicorn** [comment]
We could use an external library to load the SVG at runtime, convert it to XAML (The vector format supported by WPF), or convert it to PNG.

**Comment by SirCmpwn** [comment]
I would prefer to just have it converted to PNG.

**Comment by mrpimpunicorn** [comment]
Fixed with #199.
