### ISSUE TITLE
API for getting item icon texture coordinates

### ISSUE THREAD

**Issue by mrpimpunicorn** [SirCmpwn/TrueCraft#203]
```ItemProvider``` (or some other class) should provide a ```Vector2``` that gives us the texture coordinates for the item's icon in ```items.png```, so that the item can be rendered in the hotbar and other interfaces.

**Comment by SirCmpwn** [comment]
Yep, I was planning on implementing such a thing tonight.

**Comment by SirCmpwn** [comment]
All of the texture mappings are available [in this file](http://b.wiki.vg/json/b1.7), we can probably generate the code (and I should have done this when I first generated the item classes).

**Comment by SirCmpwn** [comment]
Done.
