### ISSUE TITLE
Window origin doesn't change with resolution

### ISSUE THREAD

**Issue by ShaunNoWay** [SirCmpwn/TrueCraft#206]
![bug](https://cloud.githubusercontent.com/assets/14033754/10212634/1473a0fe-67d0-11e5-8caf-da381eb1969b.jpg)

**Comment by SirCmpwn** [comment]
I'm not sure this is really a bug. Can't you move the window?

**Comment by mrpimpunicorn** [comment]
I'm not able to move the window; alt-tabbing is the usual solution but MonoGame keeps the mouse at the center of the TrueCraft window and it can't be moved. We can add event handlers for ```Game.OnActivated``` and ```Game.OnDeactivated``` that toggle mouse locking.

**Comment by SirCmpwn** [comment]
I see. FWIW, pressing Tab will unlock the mouse.

**Comment by ShaunNoWay** [comment]
Ah, tab did it. Thank you.
