### ISSUE TITLE
Fullscreen still doesn't work on Windows

### ISSUE THREAD

**Issue by ShaunNoWay** [SirCmpwn/TrueCraft#207]
MrPimpUnicorn posted a couple months back [(issue #132)](https://github.com/SirCmpwn/TrueCraft/issues/132) that MonoGame's fullscreen function doesn't work on Windows 7 64-bit. I just wanted to confirm that fullscreen doesn't work on my Windows machine either (Windows 10, 64-bit) and bring some attention to it in hopes of a fix.

**Comment by SirCmpwn** [comment]
...dupe of #132

**Comment by ShaunNoWay** [comment]
Crap, sorry. I probably should've just replied to that issue thread instead of just reiterating it. Sorry for my lack of Git-iquette
