### ISSUE TITLE
Currently Out of Scope Features/Issues

### ISSUE THREAD

**Issue by creatorfromhell** [SirCmpwn/TrueCraft#21]
Currently various features/issues are considered to be out of scope, and will need to be addressed at a later date. Below is a list of said features/issues by category, and will be updated as needed.
- Terrain Generation
  - [ ] Anything that requires looking at other chunks
  - [ ] Overhangs/advanced terrain generation

**Comment by SirCmpwn** [comment]
Clarification - out of scope for right now. They can be picked up later.
