### ISSUE TITLE
where is the fNbt.csproj?

### ISSUE THREAD

**Issue by lantianning** [SirCmpwn/TrueCraft#213]
I have been read the redme..
https://github.com/SirCmpwn/TrueCraft#compiling

I press your suggestion to do still error.
where is the fNbt.csproj?

**Comment by SirCmpwn** [comment]
Duplicate of #175. You didn't restore nuget packages, and you didn't actually read it.

**Comment by lantianning** [comment]
i has been restore nuget packages.i use vs 2012 and nuget.exe

**Comment by SirCmpwn** [comment]
Sorry, it's not nuget packages, it's the git submodules. You did not read the instructions.

**Comment by lantianning** [comment]
oh sorry , i try again.

**Comment by lantianning** [comment]
it work.thank you.
