### ISSUE TITLE
Command line?

### ISSUE THREAD

**Issue by RandomAltThingy** [SirCmpwn/TrueCraft#218]
It only launcher a command Elaine..

**Comment by RandomAltThingy** [comment]
Sorry, line*

**Comment by SirCmpwn** [comment]
What are you talking about

**Comment by RandomAltThingy** [comment]
I build with Visual Studio, and it launches TrueCraft.exe. This is a command line but the game does not start only a server.

**Comment by SirCmpwn** [comment]
`TrueCraft.exe` is the server. If you want to play TrueCraft, run TrueCraft.Launcher.

**Comment by RandomAltThingy** [comment]
Sorry, but what file to I run from? When I build it does not create a exe file with the launcher

**Comment by SirCmpwn** [comment]
`TrueCraft.Launcher/bin/Debug/TrueCraft.Launcher.exe`

**Comment by RandomAltThingy** [comment]
Found it

**Comment by RandomAltThingy** [comment]
Nice client! I will stop spamming this issue now.
