### ISSUE TITLE
Launcher does not hide controls from previous views

### ISSUE THREAD

**Issue by mrpimpunicorn** [SirCmpwn/TrueCraft#219]
I'm working on sky rendering in the client, when I went to debug the code, the launcher behaved like so: ![Screenshot](https://cloud.githubusercontent.com/assets/3847023/11017238/1b49f63a-8567-11e5-8818-59c2f0b20773.PNG) This didn't happen before, any ideas?

**Comment by SirCmpwn** [comment]
I can think of things that would cause that. Can you reproduce it consistently? What are the steps?

**Comment by mrpimpunicorn** [comment]
Yeah, I can reproduce it every time I start the launcher. On my Windows 10 x64 machine:
- Compile with TrueCraft.Launcher as main project.
- Run TrueCraft.Launcher in Debug mode.
- Switch to a different 'view'; singleplayer, multiplayer, etc.

On a side note, the server almost always crashes instantly after I create and join a singleplayer world. I'm getting exceptions from multiple parts of the code so I'll have to look at it a bit more before filling another issue for it.

**Comment by SirCmpwn** [comment]
I can reproduce this, too. It probably has something to do with offline mode.
