### ISSUE TITLE
iOS and/or tvOS port of TrueCraft? (to run on Apple iPhone/iPad/AppleTV)

### ISSUE THREAD

**Issue by deathcap** [SirCmpwn/TrueCraft#226]
Interested in whether it would be feasible to port TrueCraft to support iOS (for iPhone and iPad) or tvOS (for AppleTV 4th generation).

If so perhaps TrueCraft could be a neat alternative to Minecraft Portable Edition (MCPE) on iOS, which uses a different protocol than Minecraft PC edition (= unable to connect to PC, without multi-protocol servers e.g. [Dragonet](https://github.com/DragonetMC/Dragonet)). The first step would probably be to get TrueCraft to run on Mac OS X (#225), then build for iOS, port the shaders to OpenGL ES and/or Metal if needed, add multi-touch input support, and so on. tvOS support with the remote or 3rd party game controllers could come later, but would be comparatively straightforward once iOS is supported. Users could [sideload](https://www.reddit.com/r/iossideload) TrueCraft without involving an App Store.

Found some discussion of iOS support in https://github.com/SirCmpwn/TrueCraft/issues/170 [MonoGame](https://en.wikipedia.org/wiki/MonoGame) as used by TrueCraft supports iOS. [Xamarin Platform on OS X](https://xamarin.com/download) also supports iOS.

**Comment by Gbear605** [comment]
As of last work on TrueCraft OS X, Mono did not support 64 bit with it's most recent versions, which TrueCraft requires. I see that now it does support a preview 64 bit version, so I am testing it now.

**Comment by SirCmpwn** [comment]
MonoGame supports iOS, but I doubt that the TrueCraft client will run on it as-is. We use multithreading and we don't use PCL networking. It is feasible, though.

**Comment by RandomAltThingy** [comment]
Just as a side note, Dragonet is dead. Come check out [DragonetMC/DragonProxy](GitHub.com/DragonetMC/DragonProxy)

**Comment by RandomAltThingy** [comment]
I may also get a team of iOS devs to port it. I know some guys.
