### ISSUE TITLE
Compatibility with 1.8.x servers.

### ISSUE THREAD

**Issue by mathwhiz1212** [SirCmpwn/TrueCraft#230]
Please add compatibility with 1.8.x servers. I run a server with 1.8.x series mostly because of performance increases and would like to be able to connect with TrueCraft. At the very least least please make it compatible with Cuberite.

**Comment by SirCmpwn** [comment]
lol

**Comment by mathwhiz1212** [comment]
So, I'm taking that as you want to keep this to the 17.3 beta as a simple sandbox game.

**Comment by mathwhiz1212** [comment]
Is that correct?
