### ISSUE TITLE
(how to get a stacktrace on Windows?)

### ISSUE THREAD

**Issue by akavel** [SirCmpwn/TrueCraft#231]
Sorry for posting it as an "issue", but not sure where/how to find this info.

The game's crashing for me on Windows (running through the "Launcher"). I can't find any logfile anywhere afterwards; is it possible to get access to a stacktrace somehow? I understand this is .NET, so I suppose it should be possible? I'd be curious to have a look where the crash originates and maybe look around a little bit.

**Comment by SirCmpwn** [comment]
You can run the client directly: `TrueCraft.Client.exe <server> <username>`

**Comment by akavel** [comment]
I want to run single-player, what should I enter as server?

**Comment by SirCmpwn** [comment]
Run a server on localhost. Run `TrueCraft.exe` at the same time and enter the server as `localhost`. Singleplayer in TrueCraft works like this, it just does it transparently through the launcher. For debugging purposes you just have to run a server yourself.

**Comment by akavel** [comment]
Hm, so there are two things now:

1. it seems the crash actually happens in the server (and only in some
"worker thread"); so, first success here in that I got a stacktrace from
the server - thanks!
2. still, the client seems to actually run as a purely-windowed app - no
console output even when run from cmd, and it "disconnects" from cmd
immediately (a new prompt shows up in cmd as the window with graphics opens
on the side). Having it print something somewhere would still be hugely
valuable. Though it seems to actually continue working after the "worker
thread" in server crashes, but it's hard to tell if it didn't complain at
some point too.

**Comment by SirCmpwn** [comment]
I don't really know how to help you. I don't use Windows.

**Comment by akavel** [comment]
I've seen that SDL apps/games seem to apparently capture all the console output on Windows to files named quite simply stdout.log & stderr.log (or something similar). This seems like the path of least resistance on Windows. Though I can't say if that's easy or hard in .NET/MonoGame IIUC. But just saying now, in case this would bring something to your mind. 

That said, at that point I understand that's more or less all you can help me without writing some new code, so I'm closing this "issue", given that it was meant exactly purely as a quick question from the beginning. Thanks! :)

**Comment by mrpimpunicorn** [comment]
Changing TrueCraft.Client's project type from Windows Forms to Console while debugging is probably what you're looking for.

**Comment by akavel** [comment]
Yeah, but I was curious it I can try to have a quick look just by browsing
the code on github, without downloading VS or MonoDevelop/whatever.

On Sat, Mar 5, 2016 at 5:35 PM, William Moorehouse <notifications@github.com
