### ISSUE TITLE
Launching Truecraft

### ISSUE THREAD

**Issue by rafdog1223** [SirCmpwn/TrueCraft#250]
Hey (: 
I have downloaded truecraft and i have OpenAL installed and .NET 4.5 but every time I try clicking play it just relaunches the launcher.

**Comment by SirCmpwn** [comment]
Windows has issues. Use Linux.

**Comment by rafdog1223** [comment]
Shouldnt truecraft work on all OS though?

**Comment by LavenderMoon** [comment]
I'm using Windows and I can run TrueCraft just fine. @rafdog1223, can you create a world and hit play?

**Comment by LavenderMoon** [comment]
Also, what directory did you extract TrueCraft to? If it's in your Program Files directory, try moving it to "C:/Games/TrueCraft/" or a similar directory.

**Comment by rafdog1223** [comment]
I can create a world and hit play but once I hit play it closes the launcher and relaunches it, Ill try what you said though

**Comment by rafdog1223** [comment]
its in ThisPC> Downloads > TrueCraft-latest > TrueCraft    is there any problem here

**Comment by LavenderMoon** [comment]
Not as far as I know. What version of Windows are you running?

**Comment by flushienime** [comment]
same here, i'm using window 10, have installed openAL already, but every time I launch the game, it just relaunches
