### ISSUE TITLE
Crash on modern ping packet

### ISSUE THREAD

**Issue by jackmawer** [SirCmpwn/TrueCraft#258]
The TrueCraft server seems to crash when it is pinged by a modern Minecraft client.

TODO:Screenshot.

**Comment by ComputeLinux** [comment]
lol

**Comment by bb010g** [comment]
Why would this be an issue? TrueCraft only aims to be similar to beta 1.7.3, and not even compatible at that.

**Comment by SirCmpwn** [comment]
TrueCraft aims to be compatible with b1.7.3, and this *is* a problem because it's effectively a DoS attack vector.

**Comment by jackmawer** [comment]
Awesome work! <3
