### ISSUE TITLE
Building in Monodevelop on Ubuntu

### ISSUE THREAD

**Issue by MggMuggins** [SirCmpwn/TrueCraft#265]
Mono says that "The type or namespace fNbt could not be found". This is clearly a dependency issue. I'm completely new to C# and Mono, so I'm wondering what the best course of action here is.

**Comment by SirCmpwn** [comment]
You failed to follow [the instructions](https://github.com/SirCmpwn/TrueCraft#compiling) correctly. The particular instruction you failed to follow is written in bold.

**Comment by MggMuggins** [comment]
Is there any particular reason for the recursive clone? It didn't seem to me that it was entirely necessary, and there was no explanation as to what it was doing. Now that I have the repo cloned, is there any way to bring down whatever that would bring down without having to clone the whole thing over again?

**Comment by SirCmpwn** [comment]
Of course there's a reason for it. Generally speaking if an instruction is written in bold it's not because it's unnecessary.

    git submodule update --init

**Comment by MggMuggins** [comment]
I apologize for not following the directions. I would appreciate a reason in the documentation, to make it more clear that the recursive clone is necessary. Thank you for both the command and the quick responses.

**Comment by phase** [comment]
Recursive cloning is used to clone the [submodules](https://github.com/SirCmpwn/TrueCraft/tree/master/externals) inside a repository with the repo.

**Comment by MggMuggins** [comment]
I figured it was something like that. Thanks.
