### ISSUE TITLE
Crash on single player launch

### ISSUE THREAD

**Issue by tyronx** [SirCmpwn/TrueCraft#274]
Microsoft.Xna.Framework.Audio.NoAudioHardwareException was unhandled
Message: An unhandled exception of type 'Microsoft.Xna.Framework.Audio.NoAudioHardwareException' occurred in MonoGame.Framework.dll
Additional information: OpenAL drivers could not be found.

**Comment by SirCmpwn** [comment]
Obtain OpenAL.
