### ISSUE TITLE
build broken with error regarding YamlDotNet

### ISSUE THREAD

**Issue by spookylukey** [SirCmpwn/TrueCraft#41]
I followed the build instructions in the README, and got this error:

    /home/luke/tmpstore/build/TrueCraft/TrueCraft/TrueCraft.csproj (default targets) ->
    /usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->
    
            Program.cs(14,7): error CS0246: The type or namespace name `YamlDotNet' could not be found. Are you missing an assembly reference?
            Configuration.cs(3,7): error CS0246: The type or namespace name `YamlDotNet' could not be found. Are you missing an assembly reference?
    
             19 Warning(s)
             2 Error(s)

I'm using latest mono as per these instructions: http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives

Thanks!

**Comment by raphaelbastide** [comment]
Same error here.

**Comment by SirCmpwn** [comment]
Sorry about that. I'll go update the build instructions.

**Comment by raphaelbastide** [comment]
> open the solution up in monodevelop
Sorry, It is still very blurry for me, how can I do that?

**Comment by SirCmpwn** [comment]
If you're on Linux, you would probably be better off using [Nuget](http://nuget.org/) directly.

**Comment by SirCmpwn** [comment]
Otherwise, `sudo apt-get install monodevelop` and run `monodevelop`, then open TrueCraft.sln from within the IDE (which will automatically restore packages).

**Comment by cyisfor** [comment]
git submodule update was what fixed it for me. The 'git clone' by itself didn't checkout the fnBt submodule.

...maybe also git submodule init?
