### ISSUE TITLE
Doesn't build in fedora

### ISSUE THREAD

**Issue by Xe** [SirCmpwn/TrueCraft#43]
Monodevelop complains about YamlDotNet (a nuget package) not being available. When trying to install nuget packages, I get this:

![](https://i.imgur.com/WWngUyq.png)

I am using:

```console
$  mono --version
Mono JIT compiler version 2.10.8 (tarball Sun Aug 17 19:00:51 UTC 2014)
Copyright (C) 2002-2011 Novell, Inc, Xamarin, Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          debugger softdebug 
	LLVM:          supported, not enabled.
	GC:            Included Boehm (with typed GC and Parallel Mark)
```

Is there anything I am missing?

**Comment by SirCmpwn** [comment]
TrueCraft requires mono 3.10 or better. Unfortunately the Fedora maintainers haven't bothered to update mono in 4 years. I'll document this in the README, thanks!
