### ISSUE TITLE
AVG False Flag

### ISSUE THREAD

**Issue by benjibobs** [SirCmpwn/TrueCraft#49]
AVG marks the compiled TrueCraft.exe (in the Debug folder) as a virus with type 'unknown' upon running - I will submit this to AVG as a false flag, however it would be good if you had any idea what may be triggering this

**Comment by SirCmpwn** [comment]
I have no clue and don't really care. TrueCraft is not malicious and I won't change its behavior to appease crappy antivirus software.

**Comment by benjibobs** [comment]
Okay, no offence intended, just thought you should know.
