### ISSUE TITLE
Blocks are still removed from inventory even when they are not successfully placed

### ISSUE THREAD

**Issue by NSDex** [SirCmpwn/TrueCraft#50]
Steps to reproduce:
1) Give yourself n torches (where n > 0)
2) Place/find a glass back
3) Attempt to place a torch against the side of the glass block

Expected Results
The torch is not placed and you still have n torches in your inventory.

Actual Results
The torch is not placed and you have n-1 torches in your inventory.

**Comment by SirCmpwn** [comment]
Looks like there's a lot missing from torch logic. I'm working on it.
