### ISSUE TITLE
ALL THE FLOWERS

### ISSUE THREAD

**Issue by robinkanters** [SirCmpwn/TrueCraft#60]
I think this is... a bit much...

![lotsofflowers](https://cloud.githubusercontent.com/assets/1043866/7481968/6b92809c-f374-11e4-8835-5aa421531a1a.png)

**Comment by SirCmpwn** [comment]
That seems like a reasonable number of flowers to me.

**Comment by robinkanters** [comment]
I've never seen that much flowers in Minecraft in my life, but okay...
