### ISSUE TITLE
/give command

### ISSUE THREAD

**Issue by robinkanters** [SirCmpwn/TrueCraft#62]
I've done a few improvements to the /give command tonight, but I'd still like to discuss/propose 2 features:

- /giveme as shortcut so you don't have to type out your name if you want to give yourself
- Possibility to give items by entering the start of someone's name. this exists in Minecraft, and I'd like to see it as a global utility (FindPlayerByPartialUsername, or something like that). Might come in handy in a lot of other places.

The first one is really easy, for the second one, though, I wouldn't immediately know where to start. Thus, before spending a lot of effort and possibly not using a very pretty solution, I'd like to discuss them.

However, I'm going to bed now, so good night :sleeping:

**Comment by SirCmpwn** [comment]
I would be supportive of the first option, but not the second. At some point we'll be adding tab completion and then the second feature won't matter too much.

**Comment by robinkanters** [comment]
Good point, agreed
