### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by mikenon** [SirCmpwn/TrueCraft#63]
Automating builds would make TrueCraft more accessible. Mono has a [docker image](https://registry.hub.docker.com/_/mono/) that automatically builds and runs projects.

Ex. Dockerfile (in project root):

```Dockerfile
FROM mono:4.0.0-onbuild
EXPOSE 25565
CMD [ "mono",  "./TrueCraft.exe" ]
```

Build with:

    docker build -t truecraft .

or, if you want to tag the image with the git commit id:

```bash
TAG=`git log --format="%H" -n 1 | cut -c1-10`; docker build -t "truecraft:$TAG" .
```

Run with:

    docker run -it --rm -p 25565:25565 truecraft

**Comment by SirCmpwn** [comment]
I agree that a Dockerfile would be useful, but I don't want to maintain one. Are you interested in taking on that responsibility?

**Comment by mikenon** [comment]
I can do that. https://github.com/mikenon/truecraft-dockerfile is what I've got.

**Comment by SirCmpwn** [comment]
Cool. How do you edit the config.yaml?

**Comment by mikenon** [comment]
Ah, yep, that's an issue. I'll get it sorted.

**Comment by mikenon** [comment]
Okay, I think I've come up with a better way for handling things.

**Comment by SirCmpwn** [comment]
Nice, looks good. What's next?
