### ISSUE TITLE
Dropped items are spasming on the ground

### ISSUE THREAD

**Issue by robinkanters** [SirCmpwn/TrueCraft#68]
Dropped items (seem to randomly) jump up and down the Z-axis.

My guess is that the server and client can't agree on the Z-position of the item

**Comment by SirCmpwn** [comment]
Yeah, physics are weird.

**Comment by UnknownShadow200** [comment]
I'm wondering if all these calls:
```CSharp
+ new Vector3(0.5)
```
in the PhysicsEngine classes in both the server and the client are responsible. This seems incorrect, as the BlockProvider returns a bounding box of [0, 1] by default, not [-0.5, 0.5].

**Comment by SirCmpwn** [comment]
That's not why. That just moves the item entity to the middle of the block it was mined from. Spasming is because TrueCraft physics are janky.

**Comment by UnknownShadow200** [comment]
Hmm. Because when I removed the '0.5' offset from the Y axis collision, it seemed to stop the problem on the ground (but not in the air)
![mcitems](https://cloud.githubusercontent.com/assets/6509348/8145894/8e5df328-125e-11e5-8ab2-1b071a43c0a5.png)
