### ISSUE TITLE
Items lie on top of tall grass

### ISSUE THREAD

**Issue by robinkanters** [SirCmpwn/TrueCraft#72]
I expected dropped items to fall through tall grass

**Comment by SirCmpwn** [comment]
The bounding box needs to be sent to null.

**Comment by robinkanters** [comment]
When I throw items onto grass now, they're rocketed into the sky, fall back and spasm out

**Comment by SirCmpwn** [comment]
Throwing items (and physics in general) is pretty buggy. It'll be better once we start rendering these things in the TrueCraft client, which does not use prediction. The official client uses lots of prediction which makes it hard to gauge how the server is handling physics.

**Comment by SirCmpwn** [comment]
Tall grass's bounding box is now null.
