### ISSUE TITLE
Cannot throw items diagonally

### ISSUE THREAD

**Issue by robinkanters** [SirCmpwn/TrueCraft#73]

**Comment by UnknownShadow200** [comment]
InteractionHandlers.HandlePlayerDiggingPacket uses MathHelper.ForwardVector, which only returns the four cardinal directions.

Probably should use a generic 'get heading based on yaw and pitch' function instead.

**Comment by SirCmpwn** [comment]
I've intentionally stopped this from working until #68 is fixed.
