### ISSUE TITLE
PCL support

### ISSUE THREAD

**Issue by Aragas** [SirCmpwn/TrueCraft#79]
How about convert TrueCraft to PCL?
I have something that I can call a "client". Runs on mobile platforms and blah blah. Still sucks a bit. Would be cool if I could run both client and server on, for example, android.
Will help, of course.

**Comment by SirCmpwn** [comment]
I'd be willing to try and change TrueCraft.API and TrueCraft.Core to PCL so long as it didn't have substantial effects on the actual functionality of the software or the quality of the codebase.

**Comment by Aragas** [comment]
I tested fNbt. It works in PCL, but will need PCLStorage or similar to interact with filesystem. All nunit test works except with filesystem

**Comment by Aragas** [comment]
fNbt ported. You can use my fork https://github.com/MineLibOrg/fNbt to test it personally. Requires .NET 4.5, if everithing is good, can make pull request.
Works as it was before.

**Comment by SirCmpwn** [comment]
Cool, will test soon.

**Comment by SirCmpwn** [comment]
This is out of scope, we've made some other choices that make it difficult to port TrueCraft to mobile targets anyway.
