### ISSUE TITLE
Launcher written with xwt

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/TrueCraft#81]
I would like to see a TrueCraft launcher built with Mono xwt (cross platform GUI toolkit for C#). Our launcher will do a bit more than the Minecraft launcher, including:

* Browsing through your singleplayer worlds
  * Launching a server and running TrueCraft.Client to connect to it for singleplayer
* Storing and browsing your saved server list
* Login and so on

**Comment by robinkanters** [comment]
It's not on the list, but at least the launcher does manual server entry already :smile:

**Comment by SirCmpwn** [comment]
It's probably not going to do anything else until we get auth servers in place.

**Comment by SirCmpwn** [comment]
We don't really need to track this with an issue at this point, I think.
