### ISSUE TITLE
Minecraftish font needed

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/TrueCraft#82]
Need a volunteer to make a font that is in the spirit of Minecraft. Should be an image (PNG) that includes characters for the ASCII set (everything less than 0x7F, feel free to omit control chars).

For reference, here's the original Minecraft [font image](https://a.pomf.se/qhjoah.png). The TrueCraft font needs to be compatible (i.e. same characters in the same places).

**Comment by TheBerkin** [comment]
I'd be happy to give this a shot.

**Comment by Aragas** [comment]
http://fontstruct.com/fontstructions/show/pixel_unicode
contains enough symbols to add even some unicode stuff. At least cyrillic would be nice.

**Comment by RockyTV** [comment]
FixedSys?

**Comment by mrpimpunicorn** [comment]
Is [Munro](http://www.fontsquirrel.com/fonts/munro) a good enough font? It's royalty-free under [this license](http://www.fontsquirrel.com/license/Munro).

**Comment by mrpimpunicorn** [comment]
Oh, nevermind, @Aragas has already found a font.

**Comment by SirCmpwn** [comment]
Munro looks a bit better to me.
