### ISSUE TITLE
Screen-Door Transparency

### ISSUE THREAD

**Issue by NSDex** [SirCmpwn/TrueCraft#84]
Unless I'm forgetting something, every "transparent" material in b1.7.3 Minecraft can be correctly rendered using a technique called "Screen Door Transparency".  The primary benefit of this technique is that you don't need to depth sort, but it requires that each pixel in a texture be either 0% or 100%.

See the first part of [this](http://www.sea-of-memes.com/LetsCode19/LetsCode19.html) article for a better description.

**Comment by SirCmpwn** [comment]
Huh, cool. We could totally use that for most blocks - the exception being water. Thanks for the link.

**Comment by NSDex** [comment]
Yes, water is the exception.  You still don't have to depth sort Water though, just render it last.

**Comment by SirCmpwn** [comment]
I imagine we'd have to depth sort it to avoid problems with several chunks that have overlapping water (each chunk is one distinct mesh).

**Comment by robinkanters** [comment]
(glass?)

**Comment by SirCmpwn** [comment]
What about glass?

**Comment by robinkanters** [comment]
doesn't glass also have partial transparency?

**Comment by SirCmpwn** [comment]
No, each pixel of a glass texture is either 100% or 0% transparent.

**Comment by robinkanters** [comment]
Does that not potentially depend on the texture pack?

**Comment by SirCmpwn** [comment]
No, for the sake of efficiency we probably just won't support semitransparent textures for anything but water.

**Comment by robinkanters** [comment]
And the portal material/"filling"?

**Comment by SirCmpwn** [comment]
Ah, that one too.

**Comment by SirCmpwn** [comment]
Maybe we can make semitransparent voxels dynamic based on the textures.

**Comment by robinkanters** [comment]
Right. We might have to consider stained glass, too. Maybe even whether we wan't to support that at all, I'd like to see it though.

**Comment by SirCmpwn** [comment]
Well, we also have to consider the eventual needs of mods.

**Comment by robinkanters** [comment]
Right, but that's for a later stage

**Comment by SirCmpwn** [comment]
It's best not to paint ourselves into a corner wrt modding (like Mojang has <_<).

**Comment by robinkanters** [comment]
True, however I think that reflection will lend itself very well for modding. Certainly more enjoyable than copying files into `.jar`'s

**Comment by SirCmpwn** [comment]
Sure, we'll load plugins from DLLs.

**Comment by robinkanters** [comment]
Anyway, this is getting off-topic. We might want to consider a chat group of some kind for communication instead of issues :blush:

**Comment by SirCmpwn** [comment]
From the readme:

>If you want to keep up with development or contribute, join #truecraft on irc.esper.net. Pull requests will be rejected from authors who have read any decompiled official Minecraft code.

**Comment by robinkanters** [comment]
I had not seen that yet

**Comment by NSDex** [comment]
In old vanilla MC, neather portals were actually rendered last (in a pass after water) which is why if you looked at a neather portal through falling water, it would appear empty.

**Comment by robinkanters** [comment]
> In old vanilla MC

is that still the case?

**Comment by NSDex** [comment]
Or Ice.  Speaking of which, Ice.

**Comment by robinkanters** [comment]
So:

- Ice
- Water
- Portal
- Potentially tinted glass

**Comment by codeisallaround** [comment]
For some more clean info, check out the following articles: http://sea-of-memes.com/summary/blog_parts.html (part 20 and 21 are especially relevant for this issue)

**Comment by robinkanters** [comment]
@codeisallaround Don't you mean 19 and 20?

**Comment by codeisallaround** [comment]
Yes correct, sorry. 

Several other parts of his blog are relevant for other Minecraft implementation topics. His C++ code is also on GitHub: https://github.com/mgoodfel/SeaOfMemes

**Comment by SirCmpwn** [comment]
Alpha test is good enough for now. I think we'll get our performance gains elsewhere.
