### ISSUE TITLE
Discussion - differences in rendering between Minecraft and TrueCraft

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/TrueCraft#87]
To what degree is it acceptable for TrueCraft to look different than Minecraft? Here's an example that just came up:

From the bottom, torches are not fully modeled in vanilla minecraft:

![2015-05-16_19 20 32](https://cloud.githubusercontent.com/assets/1310872/7668643/2d4fb8a0-fc01-11e4-8815-2ab0c267eeb1.png)

In the TrueCraft implementation, torches have a bottom:

![2015-05-16_19 27 08](https://cloud.githubusercontent.com/assets/1310872/7668652/9ac735e8-fc01-11e4-8383-9ef744961f91.png)

Which is better? Is it okay for us to deviate like this?

**Comment by UnknownShadow200** [comment]
Minecraft changed to having a bottom texture for torches in version 1.4.4.

So I think this is okay.

**Comment by SirCmpwn** [comment]
Thanks @UnknownShadow200. Anyone else want to voice an opinion? I'm also thinking about doing away with biome-specific grass and tree colors (for now).

**Comment by brudin** [comment]
Looks better with the torch bottoms.

Biome-specific grass and leaves are pretty important, though if they are trivial then I wouldn't worry about them for now as I'm sure there's other parts of the client that need to be completed in terms of rendering.  This is looking great, by the way!  Can't wait to see some AO in the future ;)

**Comment by UnknownShadow200** [comment]
It's easy to add biome colours to Leaves, as they simply can be specified as the colour component. (This only works when using grayscale leave textures)
Grass is a bit trickier and would probably require multitexturing.

You can achieve nicer transitions by blending a block with the biome colours of the eight horizontal neighbours.
![screenshot_17-05-2015-18-34-10](https://cloud.githubusercontent.com/assets/6509348/7669673/d61882e2-fcc3-11e4-8099-7d91c3de9ade.png)

**Comment by SirCmpwn** [comment]
Why is grass trickier?

**Comment by kiljacken** [comment]
Because you only want to color some of the side textures, I guess

**Comment by UnknownShadow200** [comment]
For grass sides, you first need to specify texture coordinates for the dirt part of the sides.
You then need a second set of texture coordinates for the grayscale mask(and then the colour component).

These second texture coordinates have to be drawn using "replace existing pixel from first texture coordinates, if the alpha component of this pixel in the second texture coordinates is not 0)

**Comment by SirCmpwn** [comment]
Closing this issue as it's more or less settled.
